### ISSUE TITLE
Index out of range error on first run

### ISSUE THREAD

**Issue by teoteo** [abentele/PhotosExporter#10]
Thanks for this project.
I’m trying to use it but I get this error:

> Successfully opened connection to database.
> Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
> 2021-04-12 15:18:21.395317+0200 PhotosExporter[14325:404092] Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
> (lldb) 

My ~/Library/Application Support/PhotosExporter/PhotosExporter.yaml file is: 
```
---
config:
  photosLibraryPath: /Volumes/SSDFoto/Libreria Foto.photoslibrary 
plans:
  -
    type: IncrementalFileSystemExport
    enabled: true
    name: My export
    mediaObjectFilter:
      keywordWhiteList:
      keywordBlackList:
    targetFolder: /Volumes/Foto_famiglia 
    deleteFlatPath: false
    exportOriginals: false
    exportCurrent: true
```
I’m using it on MacOS 11.2.3; the photo library in on a USB drive and the /Volumes/Foto_famiglia is a writable shared folder non a NAS.
Do you have suggestions?

<img width="1749" alt="Schermata 2021-04-12 alle 16 05 54" src="https://user-images.githubusercontent.com/789650/114407754-06281300-9ba9-11eb-8e04-932f6b777a46.png">
